# Generated by Django 4.2.4 on 2023-08-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_source", models.CharField(max_length=30)),
                ("ip_destination", models.CharField(max_length=30)),
                ("port", models.CharField(max_length=30)),
                ("agent", models.CharField(max_length=30)),
                ("datasource", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tbldata",
            },
        ),
    ]
