from django import forms
from app.models import Data

class DataForm(forms.ModelForm):
    class Meta:
        model = Data
        fields = [
            "dur", "proto", "service", "state", "spkts", "dpkts", "sbytes", "dbytes",
            "rate", "sttl", "dttl", "sload", "dload", "sloss", "dloss", "sinpkt", "dinpkt",
            "sjit", "djit", "swin", "stcpb", "dtcpb", "dwin", "tcprtt", "synack", "ackdat",
            "smean", "dmean", "trans_depth", "response_body_len", "ct_srv_src", "ct_state_ttl",
            "ct_dst_ltm", "ct_src_dport_ltm", "ct_dst_sport_ltm", "ct_dst_src_ltm", "is_ftp_login",
            "ct_ftp_cmd", "ct_flw_http_mthd", "ct_src_ltm", "ct_srv_dst", "is_sm_ips_ports",
            "attack_cat", "label",
        ]
        widgets = {
            "dur": forms.TextInput(attrs={"class": "form-control"}),
            "proto": forms.TextInput(attrs={"class": "form-control"}),
            "service": forms.TextInput(attrs={"class": "form-control"}),
            "state": forms.TextInput(attrs={"class": "form-control"}),
            "spkts": forms.TextInput(attrs={"class": "form-control"}),
            "dpkts": forms.TextInput(attrs={"class": "form-control"}),
            "sbytes": forms.TextInput(attrs={"class": "form-control"}),
            "dbytes": forms.TextInput(attrs={"class": "form-control"}),
            "rate": forms.TextInput(attrs={"class": "form-control"}),
            "sttl": forms.TextInput(attrs={"class": "form-control"}),
            "dttl": forms.TextInput(attrs={"class": "form-control"}),
            "sload": forms.TextInput(attrs={"class": "form-control"}),
            "dload": forms.TextInput(attrs={"class": "form-control"}),
            "sloss": forms.TextInput(attrs={"class": "form-control"}),
            "dloss": forms.TextInput(attrs={"class": "form-control"}),
            "sinpkt": forms.TextInput(attrs={"class": "form-control"}),
            "dinpkt": forms.TextInput(attrs={"class": "form-control"}),
            "sjit": forms.TextInput(attrs={"class": "form-control"}),
            "djit": forms.TextInput(attrs={"class": "form-control"}),
            "swin": forms.TextInput(attrs={"class": "form-control"}),
            "stcpb": forms.TextInput(attrs={"class": "form-control"}),
            "dtcpb": forms.TextInput(attrs={"class": "form-control"}),
            "dwin": forms.TextInput(attrs={"class": "form-control"}),
            "tcprtt": forms.TextInput(attrs={"class": "form-control"}),
            "synack": forms.TextInput(attrs={"class": "form-control"}),
            "ackdat": forms.TextInput(attrs={"class": "form-control"}),
            "smean": forms.TextInput(attrs={"class": "form-control"}),
            "dmean": forms.TextInput(attrs={"class": "form-control"}),
            "trans_depth": forms.TextInput(attrs={"class": "form-control"}),
            "response_body_len": forms.TextInput(attrs={"class": "form-control"}),
            "ct_srv_src": forms.TextInput(attrs={"class": "form-control"}),
            "ct_state_ttl": forms.TextInput(attrs={"class": "form-control"}),
            "ct_dst_ltm": forms.TextInput(attrs={"class": "form-control"}),
            "ct_src_dport_ltm": forms.TextInput(attrs={"class": "form-control"}),
            "ct_dst_sport_ltm": forms.TextInput(attrs={"class": "form-control"}),
            "ct_dst_src_ltm": forms.TextInput(attrs={"class": "form-control"}),
            "is_ftp_login": forms.TextInput(attrs={"class": "form-control"}),
            "ct_ftp_cmd": forms.TextInput(attrs={"class": "form-control"}),
            "ct_flw_http_mthd": forms.TextInput(attrs={"class": "form-control"}),
            "ct_src_ltm": forms.TextInput(attrs={"class": "form-control"}),
            "ct_srv_dst": forms.TextInput(attrs={"class": "form-control"}),
            "is_sm_ips_ports": forms.TextInput(attrs={"class": "form-control"}),
            "attack_cat": forms.TextInput(attrs={"class": "form-control"}),
            "label": forms.TextInput(attrs={"class": "form-control"}),
        }