from django.db import models

# Create your models here.
class Data(models.Model):
    dur = models.FloatField(default=0.0)
    proto = models.CharField(max_length=10, default="")
    service = models.CharField(max_length=10, default="")
    state = models.CharField(max_length=10, default="")
    spkts = models.IntegerField(default=0)
    dpkts = models.IntegerField(default=0)
    sbytes = models.IntegerField(default=0)
    dbytes = models.IntegerField(default=0)
    rate = models.FloatField(default=0.0)
    sttl = models.IntegerField(default=0)
    dttl = models.IntegerField(default=0)
    sload = models.FloatField(default=0.0)
    dload = models.FloatField(default=0.0)
    sloss = models.IntegerField(default=0)
    dloss = models.IntegerField(default=0)
    sinpkt = models.FloatField(default=0.0)
    dinpkt = models.FloatField(default=0.0)
    sjit = models.FloatField(default=0.0)
    djit = models.FloatField(default=0.0)
    swin = models.IntegerField(default=0)
    stcpb = models.IntegerField(default=0)
    dtcpb = models.IntegerField(default=0)
    dwin = models.IntegerField(default=0)
    tcprtt = models.FloatField(default=0.0)
    synack = models.FloatField(default=0.0)
    ackdat = models.FloatField(default=0.0)
    smean = models.FloatField(default=0.0)
    dmean = models.FloatField(default=0.0)
    trans_depth = models.IntegerField(default=0)
    response_body_len = models.IntegerField(default=0)
    ct_srv_src = models.IntegerField(default=0)
    ct_state_ttl = models.IntegerField(default=0)
    ct_dst_ltm = models.IntegerField(default=0)
    ct_src_dport_ltm = models.IntegerField(default=0)
    ct_dst_sport_ltm = models.IntegerField(default=0)
    ct_dst_src_ltm = models.IntegerField(default=0)
    is_ftp_login = models.IntegerField(default=0)
    ct_ftp_cmd = models.IntegerField(default=0)
    ct_flw_http_mthd = models.IntegerField(default=0)
    ct_src_ltm = models.IntegerField(default=0)
    ct_srv_dst = models.IntegerField(default=0)
    is_sm_ips_ports = models.IntegerField(default=0)
    attack_cat = models.CharField(max_length=50, default='Normal')
    label = models.IntegerField(default=0)

    class Meta:
        db_table = "tbldata"